### PR TITLE
make the instruction for windows into an accordion

### PR DESCRIPTION
**Pull request by The-Ludwig**
* rewritten it with jquery
* using bootstrap (like this accordion example: https://getbootstrap.com/docs/4.3/components/collapse/ )
* added a conditional include in scripts, so if the page header contains "collapse: True" it is activated
* all the pages h3 headings will be collapsable until the next h3 or h4 heading

=> Can be easily added for any other instruction via "collapse: True" in the front matter

### CODE REVIEW

**Comment by MaxNoe** [comment]
Trying in Firefox, going trough the stuff one by one results in jumping because the last part collapses as soon as one clicks on the next and one lands midway in the section, not at the start.

**Comment by MaxNoe** [comment]
And there is a "just to enable liquid" at the bottom

**Comment by The-Ludwig** [comment]
fixed it

**Comment by MaxNoe** [comment]
Like this:

```
## The Site   {.collapse}
```

**Comment by The-Ludwig** [comment]
did it like that, but I kind of think it looks weird if only some headers are collapsable...

**Pull request closed without merging**
