### PR TITLE
Windows installation update

### PR DESCRIPTION
**Pull request by LuckyJosh**
Added new installation instructions for Windows 10 using the _Windows Subsystem for Linux_.
The instructions include the following programs:

#### General
- [ ] proof reading, not even to thoroughly
- [ ] testing of instructions from start to finish, maybe by a "non-technical" person
- [ ] installation section
   - [x] instructions for all necessary software
   - [ ] order of  installation steps
- [ ] Upgrade Python version from 3.6 to 3.7 if need be
- [x] ~settings section~
- [x] testing section
- [x] ~change screenshots containing ConEmu to not include the menu and status bar,
      if we remove ConEmu entirely~ **ConEmu is a small pain to setup but I find the default shell
to be a small pain to use (If I have to hear this windows warning sound once more ... :rage1:)**
- [x] ~add folding (or some kind of picture cycle/carousel) of the different (software) sections to reduce the intimidating look of +49 A4 Pages~ **Turned out to be much harder to implement than expected, maybe for next year**

#### Windows Software
- [x]  Sumatra PDF
   - [x] download & installation
   - [x] settings
   - [x] ~adding SumatraPDF to `PATH` to be able to open it from the WSL?~ **Did not get that to work but a alias works great**
   - [x] added instruction for `sumatrapdf` alias

- [x] ~Atom~
    - [x] ~download & installation~
    - [x] ~settings~
       - [x] ~package installation `language-latex`~

- [x] VS Code
   - [x] download & installation
   - [x] settings
       - [x] setting language to _english_?
       - [x] maybe some "essential" packages
           - [x] ~python?~ **The in-build syntax highlighting is good enough for the beginning.**
           - [x] ~latex-workshop?~ **This adds to much features at once. Replaced by only syntax highlighting as well.**
           - [x] LaTeX language support **Mainly adds syntax highlighting for BibTeX, LaTeX and TeX**

- [x] Xserver
    - [x] download & installation
    - [x] settings
        - [x] adding DISPLAY envvar to `.bashrc`

- [x] WSL
   - [x] activation
   - [x] installation

- [x] git and make
   - [x] installation
   - [x] git settings
   - [x] testing

- [x]  ConEmu
    - [x] download & installation
    - [x] setup for WSL

#### Linux Software (WSL)
- [x] Anaconda
   - [x] download & installation
       - [x] dont add conda to the path
       - [x] add path to conda.sh and `conda activate` to `.bashrc`
   - [x] uncertainties
   - [x] updates
   - [x] testing

- [x] TexLive
   - [x] download & installation
   - [x] updates
   - [x] testing
   - [x] prepending installation path to `PATH`

Feel free to add new tasks/subtask to the todo list above.

Some additional ideas:

@mennthor Send me [this link](https://char.gd/blog/2017/how-to-set-up-the-perfect-modern-dev-environment-on-windows) to a blog post on a modern dev-env on windows. The Terminal
[Hyper](https://github.com/zeit/hyper) looks quite neat and the setup would be a bit easier
then ConEmu( e.g. we could supply the `.hyper.js` settings file). On the other hand, using this may also open up the way for many new yet unknown issues, although it worked fine when I tried it.

Regarding the current editor of choice `atom`. Should we think about changing to VSCode atleast longterm?
I am personally heavily biased towards VSCode but there are some objective arguments to be made
for VSC. First of all in some case the installation of Atom resulted in in rather strange behaviour (e.g. the installation path wasnt the same on all windows installations, which resulted in some issue if forgot the details of). VSC works very reliably on all platforms I am using it on (Ubuntu, Win10).
My second point would be that VSC is (or atleast) still feels faster then atom (but that impression could be caused by my personal bias).
Last but not least, atom may not be around anymore if microsoft decides to ditch it someday.

### CODE REVIEW

**Comment by MaxNoe** [comment]
After looking at it for a bit,  I would also prefer vs code over atom.

The hard par for me was getting the menu integration on windows, I had to create registry keys by hand!

**Comment by MaxNoe** [comment]
Also, the powershell window got a lot better that good old cod.exe, so maybe we don't need to install a new terminal at all and just use something like this:
https://www.howtogeek.com/270810/how-to-quickly-launch-a-bash-shell-from-windows-10s-file-explorer/

**Comment by LuckyJosh** [comment]
@MaxNoe Should we then just provide a link to the `.reg` file for the registry changes with the instructions? 
Or maybe just a batch file for opening bash in the designated "Praktikum"-Folder?

**Comment by LuckyJosh** [comment]
On another note:
As  you can see the instructions include a lot more screenshots now (printing the webpage would amount in 49 A4 Pages). Can we add some kind of folding of the different sections?

**Comment by MaxNoe** [comment]
> Setting language to german?

When I downloaded it, it had german language settings and I had to change it to english. 
We should make sure it's english.

**Comment by LuckyJosh** [comment]
@MaxNoe yeah I probably ment to say english, my installation is german as well :man_facepalming: :sweat_smile: :

**Comment by LuckyJosh** [comment]
The [bootstrap accordion](https://getbootstrap.com/docs/4.0/components/collapse/#accordion-example) is quite a hassle to use with the markdown installation instructions.
Is there an obvious way to use markdown inside the accordion that I have not found?

Form the link above I used the
```html
<div class="card">
    <div class="card-header" id="headingOne">
      <h5 class="mb-0">
        <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Collapsible Group Item #1
        </button>
      </h5>
    </div>
    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
      <div class="card-body">
        ...
      </div>
    </div>
  </div>
```
Since markdown does not seem to work inside of html tags I found this fix, using a `<span markdown="1">` tag:

```html
<div class="card">
    <div class="card-header" id="headingOne">
      <h5 class="mb-0">
        <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Collapsible Group Item #1
        </button>
      </h5>
    </div>
    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
      <span class="card-body" markdown="1">
        ...
      </span>
    </div>
  </div>
```
But the markdown inside the `<span>` tag does not work properly.
For example lists do not work, the apperiance code blocks changes and the
spacings between text and images is unreliable. 

I have pushed a [new branch](https://github.com/pep-dortmund/homepage-toolbox/tree/windows-installation-update-with-accordion) with some accordions to demonstrate the problems.

**Comment by LuckyJosh** [comment]
Using the VSCode (installed on Windows) for the git commit messages 
via `git config --global core.editor "code --wait"` does not seem to work.
The file opened is a empty file as opposed to the default template (with comments in it).

Instead of using the WindowsPath to the Test-Repo `C:\Users\josh\Desktop\test_repo\.git`
 `git commit` generates the directory structure `C:\mnt\c\Users\josh\Desktop\test_repo\.git`
because the Windows Filesystem is mounted under the Path  `\mnt\c\Users\josh\Desktop\test_repo\.git` in the WSL.

I have not looked into it, but it feels like not being worth the effort for trying to fix this.
I guess for now `nano` has to suffice for the windows users. :thinking:

**Pull request merged**
